const SIGN_UP = 'SIGN_UP';
const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
const SIGN_UP_ERROR = 'SIGN_UP_ERROR';

const SIGN_IN = 'SIGN_IN';
const SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS';
const SIGN_IN_ERROR = 'SIGN_IN_ERROR';

const MAKE_POST = 'MAKE_POST';
const MAKE_POST_SUCCESS = 'MAKE_POST_SUCCESS';
const MAKE_POST_ERROR = 'MAKE_POST_ERROR';

const FETCH_POSTS = 'FETCH_POSTS';
const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
const FETCH_POSTS_ERROR = 'FETCH_POSTS_ERROR';

const FETCH_COMMENTS = 'FETCH_COMMENTS';
const FETCH_COMMENTS_SUCCESS = 'FETCH_COMMENTS_SUCCESS';
const FETCH_COMMENTS_ERROR = 'FETCH_COMMENTS_ERROR';

const SEND_COMMENT = 'SEND_COMMENT';
const SEND_COMMENT_SUCCESS = 'SEND_COMMENT_SUCCESS';
const SEND_COMMENT_ERROR = 'SEND_COMMENT_ERROR';

const LOAD_COMMENTS = 'LOAD_COMMENTS';
const LOAD_COMMENTS_SYNC = 'LOAD_COMMENTS_SYNC';

const LOG_OUT = 'LOG_OUT';
const LOAD_SESSION = 'LOAD_SESSION';

export {
  SIGN_UP,
  SIGN_UP_SUCCESS,
  SIGN_UP_ERROR,
  SIGN_IN,
  SIGN_IN_SUCCESS,
  SIGN_IN_ERROR,
  MAKE_POST,
  MAKE_POST_SUCCESS,
  MAKE_POST_ERROR,
  FETCH_POSTS,
  FETCH_POSTS_SUCCESS,
  FETCH_POSTS_ERROR,
  FETCH_COMMENTS,
  FETCH_COMMENTS_SUCCESS,
  FETCH_COMMENTS_ERROR,
  SEND_COMMENT,
  SEND_COMMENT_SUCCESS,
  SEND_COMMENT_ERROR,
  LOAD_COMMENTS,
  LOAD_COMMENTS_SYNC,
  LOG_OUT,
  LOAD_SESSION,
};